const cartExample = [
  {
    id: 23,
    info: "Some info about shoes, that we see on the product page. This can be an additional description or information about the quality or year of manufacture. In general, this is information that will be unique to each shoe, which will have to attract the customer.",
    href: "./product.html",
    name: "Kappa Banda Coen",
    image: "../images/shoes/Kappa-Banda-Coen.jpg",
    price: 90,
    size: ["39", "40", "41", "42", "43", "44", "45"],
    sex: "male",
    type: "retro",
    brand: "Kappa",
    sale: 0.05,
    views: 7,
    createdAt: new Date("2023-03-17"),
    qty: {
      39: 6,
      40: 7,
      41: 4,
      42: 3,
      43: 9,
      44: 10,
      45: 3,
    },
    userSize: "41",
    userQty: 1,
  },
  {
    id: 24,
    info: "Some info about shoes, that we see on the product page.",
    href: "./product.html",
    name: "Adidas x Parley Ultraboost 5.0",
    image: "../images/shoes/Adidas-X-Parley-Ultraboost-5.0-DNA.jpg",
    price: 240,
    size: ["38", "39", "40", "41", "42"],
    sex: "male",
    type: "running",
    brand: "Adidas",
    sale: 0.2,
    views: 14,
    createdAt: new Date("2023-03-16"),
    qty: {
      39: 6,
      40: 7,
      41: 4,
      42: 3,
      43: 9,
      44: 10,
      45: 3,
    },
    userSize: "39",
    userQty: 1,
  },
  {
    id: 25,
    info: "Some info about shoes, that we see on the product page.",
    href: "./product.html",
    name: "Nike Air Max 97",
    image: "../images/shoes/Nike-Air-Max-97.jpg",
    price: 190,
    size: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    sex: "male",
    type: "running",
    brand: "Nike",
    sale: 0,
    views: 8,
    createdAt: new Date("2023-03-15"),
    qty: {
      35: 8,
      36: 2,
      37: 5,
      38: 1,
      39: 6,
      40: 7,
      41: 4,
      42: 3,
      43: 9,
      44: 10,
      45: 3,
    },
    userSize: "42",
    userQty: 1,
  },
];

export { cartExample };
